### ISSUE TITLE
Data reading example

### ISSUE THREAD

**Issue by DN2048** [MikuAuahDark/SnakeNBT#1]
Hello,

Can you provide an example on how to get the information of the NBT file? For example, after opening how do I list all the names and values there?
After opening the file like so
```
with open(str(self._entities_path) + "/r.0.0.mca", "rb") as f:
    nbt_data = snakenbt.load(f, preserve_tag_type=True)
    print(nbt_data)
```
I get "None" so I'm assuming I'm doing something wrong or this project has nothing to do with the Minecraft's NBT format.

**Comment by MikuAuahDark** [comment]
Right. SnakeNBT only deals with NBT data.

To reduce misconception in the future, NBT is a general purpose binary format. It's true that NBT format is developed by Minecraft, however apps are allowed to use NBT in their apps too without having it to do with Minecraft.

[To read NBT data in `*.mca` file](https://minecraft.wiki/w/Region_file_format):
1. Skip the first 8192 bytes.
2. Read the amount to read as 4 byte integer, big endian. Store this as `length`.
3. Read 1 byte. This indicate  compression scheme (1 = gzip, 2 = zlib, 3 = uncompressed)
4. Read `length` bytes.
5. If compression scheme is not 3, perform decompress on data from step 4.

This Python script works.
```py
import gzip
import io
import struct
import zlib

import snakenbt

with open("r.0.0.mca", "rb") as f:
    f.seek(8192, io.SEEK_SET)
    remaining: int = struct.unpack(">I", f.read(4))[0]
    compression_scheme = f.read(1)[0]
    compressed_data = f.read(remaining)

    match compression_scheme:
        case 1:
            decompressed = gzip.decompress(compressed_data)
        case 2:
            decompressed = zlib.decompress(compressed_data)
        case 3:
            decompressed = compressed_data
        case 4:
            raise RuntimeError("LZ4 is not supported")
        case _:
            raise RuntimeError("Unknown compression")
    
    nbt_data = snakenbt.loads(decompressed)
```
